#!/bin/bash
# modules/shell.sh - Shell configuration module
# Installs shell config, plugins, and prompts (NO Starship)

_MODULE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$_MODULE_DIR/../lib/utils.sh"
source "$_MODULE_DIR/../lib/platform.sh"
source "$_MODULE_DIR/../lib/sudo.sh"

# Install shell enhancements for macOS (zsh plugins)
install_shell_macos() {
    info "Installing zsh plugins (macOS)"

    # Install zsh plugins via Homebrew
    local plugins=(
        "zsh-autosuggestions"
        "zsh-syntax-highlighting"
        "zsh-completions"
    )

    for plugin in "${plugins[@]}"; do
        if brew list "$plugin" &>/dev/null; then
            skip "$plugin already installed"
        else
            brew install "$plugin" >>"$LOG_FILE" 2>&1 && success "Installed $plugin" || error "Failed to install $plugin"
        fi
    done
}

# Install shell enhancements for Linux (ble.sh for bash)
install_shell_linux() {
    info "Installing ble.sh for bash enhancements (Linux)"

    local blesh_dir="$HOME/.local/share/blesh"
    local blesh_file="$blesh_dir/ble.sh"

    # Check if ble.sh is already installed
    if [[ -f "$blesh_file" ]]; then
        success "ble.sh already installed"
        return 0
    fi

    # Create blesh directory
    mkdir -p "$blesh_dir"

    # Download and install ble.sh (pre-built nightly)
    info "Downloading ble.sh..."
    if curl -fsSL https://github.com/akinomyoga/ble.sh/releases/download/nightly/ble-nightly.tar.xz | \
       tar xJf - -C "$blesh_dir" --strip-components=1 >>"$LOG_FILE" 2>&1; then
        success "ble.sh installed successfully"
    else
        error "Failed to install ble.sh"
        return 1
    fi

    # Install zsh plugins if zsh is available (optional for Linux)
    if command -v zsh &>/dev/null; then
        info "Installing zsh plugins via apt..."
        pkg_install zsh-autosuggestions zsh-syntax-highlighting >>"$LOG_FILE" 2>&1 && \
            success "Installed zsh plugins" || skip "Could not install zsh plugins"
    fi
}

# Generate bashrc from template
generate_bashrc() {
    local rc_file="$HOME/.bashrc"
    local shell_config_dir="$HOME/.bash"

    info "Generating .bashrc"

    # Create .bashrc content
    cat > "$rc_file" << 'BASHRC_EOF'
# ~/.bashrc - Zen Configuration
# Generated by Zen (全) - Complete Terminal Environment

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# ble.sh - Bash Line Editor (syntax highlighting + autosuggestions)
# Must be sourced at the beginning of bashrc
if [[ -f "$HOME/.local/share/blesh/ble.sh" ]]; then
  source "$HOME/.local/share/blesh/ble.sh" --noattach --rcfile "$HOME/.blerc"
fi

# History configuration
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

# Update window size after each command
shopt -s checkwinsize

# Enable programmable completion features
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Better directory navigation
shopt -s autocd
shopt -s cdspell
shopt -s dirspell

# Enable ** globstar
shopt -s globstar

# Environment variables
# Use nvim if available, otherwise fall back to vi
if command -v nvim &> /dev/null; then
  export EDITOR=nvim
  export VISUAL=nvim
else
  export EDITOR=vi
  export VISUAL=vi
fi
export PAGER=less
export TERM=xterm-256color

# Path configuration
export PATH="$HOME/.local/bin:$PATH"

# UV (Python) configuration
export UV_SYSTEM_PYTHON=1

# FZF configuration
if command -v fd &> /dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
else
  export FZF_DEFAULT_COMMAND='find . -type f'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND='find . -type d'
fi
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --inline-info --preview "bat --color=always --style=numbers {} 2>/dev/null || cat {}" --preview-window=right:60%:wrap'
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {} 2>/dev/null || cat {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --level=2 --color=always {} 2>/dev/null || ls -la {} | head -200'"

# bat configuration
export BAT_THEME="TwoDark"

# Less configuration
export LESS='-R -F -X -i -M'
export LESSCHARSET='utf-8'

# Docker configuration
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

# Zen setup directory
export ZEN_SETUP_DIR="$HOME/.local/share/zen-setup"

# Load modular configurations
[ -f ~/.bash/prompt ] && source ~/.bash/prompt
[ -f ~/.bash/aliases ] && source ~/.bash/aliases
[ -f ~/.bash/functions ] && source ~/.bash/functions

# Initialize zoxide (smart cd)
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init bash)"
fi

# Initialize fzf
if command -v fzf &> /dev/null; then
  [ -f ~/.fzf.bash ] && source ~/.fzf.bash
  [ -f /usr/share/doc/fzf/examples/completion.bash ] && source /usr/share/doc/fzf/examples/completion.bash
  [ -f /usr/share/doc/fzf/examples/key-bindings.bash ] && source /usr/share/doc/fzf/examples/key-bindings.bash
fi

# GitHub CLI completions
if command -v gh &> /dev/null; then
  eval "$(gh completion -s bash)"
fi

# UV (Python) completion
if command -v uv &> /dev/null; then
  eval "$(uv generate-shell-completion bash)"
fi

# Local customizations (not managed by Zen)
[ -f ~/.bashrc.local ] && source ~/.bashrc.local

# Welcome message
if [ -t 0 ]; then
  if command -v fastfetch &> /dev/null; then
    fastfetch
  fi
fi

# ble.sh - Attach at the end of bashrc
[[ ${BLE_VERSION-} ]] && ble-attach
BASHRC_EOF

    success "Generated .bashrc"
}

# Generate zshrc from template
generate_zshrc() {
    local rc_file="$HOME/.zshrc"
    local shell_config_dir="$HOME/.zsh"

    info "Generating .zshrc"

    # Create .zshrc content
    cat > "$rc_file" << 'ZSHRC_EOF'
# ~/.zshrc - Zen Configuration
# Generated by Zen (全) - Complete Terminal Environment

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# History configuration
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=20000
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY

# Better directory navigation
setopt AUTO_CD
setopt AUTO_PUSHD
setopt PUSHD_IGNORE_DUPS
setopt PUSHD_SILENT

# Enable globbing
setopt EXTENDED_GLOB
setopt NOMATCH

# Environment variables
# Use nvim if available, otherwise fall back to vi
if command -v nvim &> /dev/null; then
  export EDITOR=nvim
  export VISUAL=nvim
else
  export EDITOR=vi
  export VISUAL=vi
fi
export PAGER=less
export TERM=xterm-256color

# Path configuration
export PATH="$HOME/.local/bin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"

# UV (Python) configuration
export UV_SYSTEM_PYTHON=1

# FZF configuration
if command -v fd &> /dev/null; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
else
  export FZF_DEFAULT_COMMAND='find . -type f'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
  export FZF_ALT_C_COMMAND='find . -type d'
fi
export FZF_DEFAULT_OPTS='--height 40% --layout=reverse --border --inline-info --preview "bat --color=always --style=numbers {} 2>/dev/null || cat {}" --preview-window=right:60%:wrap'
export FZF_CTRL_T_OPTS="--preview 'bat --color=always --style=numbers --line-range=:500 {} 2>/dev/null || cat {}'"
export FZF_ALT_C_OPTS="--preview 'eza --tree --level=2 --color=always {} 2>/dev/null || ls -la {} | head -200'"

# bat configuration
export BAT_THEME="TwoDark"

# Less configuration
export LESS='-R -F -X -i -M'
export LESSCHARSET='utf-8'

# Docker configuration
export DOCKER_BUILDKIT=1
export COMPOSE_DOCKER_CLI_BUILD=1

# Zen setup directory
export ZEN_SETUP_DIR="$HOME/.local/share/zen-setup"

# Enable completion system
autoload -Uz compinit
compinit

# Load modular configurations
[ -f ~/.zsh/prompt ] && source ~/.zsh/prompt
[ -f ~/.zsh/aliases ] && source ~/.zsh/aliases
[ -f ~/.zsh/functions ] && source ~/.zsh/functions

# Initialize zoxide (smart cd)
if command -v zoxide &> /dev/null; then
  eval "$(zoxide init zsh)"
fi

# Initialize fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
if type brew &>/dev/null; then
  [ -f $(brew --prefix)/opt/fzf/shell/completion.zsh ] && source $(brew --prefix)/opt/fzf/shell/completion.zsh
  [ -f $(brew --prefix)/opt/fzf/shell/key-bindings.zsh ] && source $(brew --prefix)/opt/fzf/shell/key-bindings.zsh
fi

# GitHub CLI completions
if command -v gh &> /dev/null; then
  eval "$(gh completion -s zsh)"
fi

# UV (Python) completion
if command -v uv &> /dev/null; then
  eval "$(uv generate-shell-completion zsh)"
fi

# Homebrew completion (macOS only)
if type brew &>/dev/null; then
  FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"
  FPATH="$(brew --prefix)/share/zsh-completions:${FPATH}"
fi

# Zsh plugins (macOS: Homebrew, Linux: apt)
if type brew &>/dev/null; then
  # macOS: Plugins installed via Homebrew
  [ -f "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ] && \
    source "$(brew --prefix)/share/zsh-autosuggestions/zsh-autosuggestions.zsh"

  [ -f "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ] && \
    source "$(brew --prefix)/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
else
  # Linux: Plugins installed via apt
  [ -f /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh ] && \
    source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh

  [ -f /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ] && \
    source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi

# Autosuggestion settings
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#888888"
ZSH_AUTOSUGGEST_STRATEGY=(history completion)
ZSH_AUTOSUGGEST_BUFFER_MAX_SIZE=20

# Completion styling
zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-zA-Z}={A-Za-z}' 'r:|[._-]=* r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' special-dirs true

# Key bindings (emacs-style)
bindkey -e
bindkey '^[[A' history-search-backward
bindkey '^[[B' history-search-forward
bindkey '^[[1;5C' forward-word
bindkey '^[[1;5D' backward-word

# Local customizations (not managed by Zen)
[ -f ~/.zshrc.local ] && source ~/.zshrc.local

# Welcome message
if [ -t 0 ]; then
  if command -v fastfetch &> /dev/null; then
    fastfetch
  fi
fi
ZSHRC_EOF

    success "Generated .zshrc"
}

# Copy shell configuration files
copy_shell_configs() {
    local shell=$(detect_shell)
    local shell_config_dir="$HOME/.$shell"
    local config_source_dir="$_MODULE_DIR/../config/shell"

    # Create shell config directory
    mkdir -p "$shell_config_dir"
    mkdir -p "$HOME/.local/bin"

    info "Copying shell configuration files"

    # Copy aliases
    if [[ -f "$config_source_dir/bash_aliases" ]]; then
        cp "$config_source_dir/bash_aliases" "$shell_config_dir/aliases"
        success "Copied aliases"
    else
        warn "bash_aliases not found in $config_source_dir"
    fi

    # Copy functions
    if [[ -f "$config_source_dir/bash_functions" ]]; then
        cp "$config_source_dir/bash_functions" "$shell_config_dir/functions"
        success "Copied functions"
    else
        warn "bash_functions not found in $config_source_dir"
    fi

    # Copy prompt (platform-specific)
    if is_macos; then
        if [[ -f "$config_source_dir/zsh_prompt" ]]; then
            cp "$config_source_dir/zsh_prompt" "$shell_config_dir/prompt"
            success "Copied zsh prompt"
        else
            warn "zsh_prompt not found in $config_source_dir"
        fi
    else
        if [[ -f "$config_source_dir/bash_prompt" ]]; then
            cp "$config_source_dir/bash_prompt" "$shell_config_dir/prompt"
            success "Copied bash prompt"
        else
            warn "bash_prompt not found in $config_source_dir"
        fi
    fi

    # Copy inputrc (Linux only)
    if is_linux; then
        if [[ -f "$config_source_dir/inputrc" ]]; then
            cp "$config_source_dir/inputrc" "$HOME/.inputrc"
            success "Copied inputrc"
        else
            warn "inputrc not found in $config_source_dir"
        fi
    fi

    # Copy blerc (Linux only)
    if is_linux; then
        if [[ -f "$config_source_dir/blerc" ]]; then
            cp "$config_source_dir/blerc" "$HOME/.blerc"
            success "Copied blerc"
        else
            warn "blerc not found in $config_source_dir"
        fi
    fi

    # Create .hushlogin on macOS
    if is_macos; then
        touch "$HOME/.hushlogin"
        success "Created .hushlogin"
    fi
}

# Main installation function
install_shell() {
    print_section "🐚 Installing Shell Configuration"

    # Install platform-specific shell enhancements
    if is_macos; then
        install_shell_macos
    elif is_linux; then
        install_shell_linux
    fi

    # Copy shell configuration files (will be moved from roles/ in reorganization phase)
    copy_shell_configs

    # Generate shell RC file
    local shell=$(detect_shell)
    if [[ "$shell" == "zsh" ]]; then
        generate_zshrc
    else
        generate_bashrc
    fi

    success "Shell configuration installed"
}

# Export the main function
export -f install_shell
